### ISSUE TITLE
Zombie scan and copy tasks

### ISSUE THREAD

**Issue by dag-erling** [unioslo/tsdfx#38] opened 2015-11-14 14:29 UTC
The zombie issue which was fixed in 8a1cc30a5f8739667b22ca034bdd76be08d176d7 seems to have reappeared. I suspect that it was reintroduced by 858f037d668c70dbcca9d502c59f2e269af715b7. We need to find a way to reproduce it in a test environment.

**Comment by petterreinholdtsen** [comment] 2015-11-14 18:08
[Dag-Erling Smørgrav]

> The zombie issue which was fixed in
> 8a1cc30a5f8739667b22ca034bdd76be08d176d7 seems to have reappeared. I
> suspect that it was reintroduced by
> 858f037d668c70dbcca9d502c59f2e269af715b7. We need to find a way to
> reproduce it in a test environment.

As far As I know, the 858f037d668c70dbcca9d502c59f2e269af715b7 change is
not yet in production.

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment] 2015-11-16 13:50
[Petter Reinholdtsen]

> As far as I know, the 858f037 change is not yet in production.

You're right, so it has to be the same problem that cropped up again. I suspect that it is caused by scan tasks that run for a long time and return a large number of files. We have a few projects with tens of thousands of files.

**Comment by petterreinholdtsen** [comment] 2015-11-18 08:19
The problem seem to be caused by all copier processes being occupied by lots of large files being compied.  We discussed a solution earlier, where we provided two copier pools, one for large files and one for small files.  A new file would be assigned one of the small file copiers and start the copying.  After copying some threshold number of bytes, the small file copier would exit and the next time the file was found by a scanner, it would be assigned to a copier from the large file pool.  This way many large files would not block all small files from being copied.

**Comment by dag-erling** [comment] 2015-11-18 08:48
No, long-lived copier processes will not cause this. Zombie processes are processes that haven't yet been collected by the parent, and copier processes don't cause the parent to block. The only plausible cause I can think of is that the parent is busy processing the output from a very busy scanner process. When I checked fx02 this morning, it had seven active and one zombie copiers, and one active and seven zombie scanners. The one active scanner was working on a directory with ~30k files (2 MB of output) and had been running for >10 minutes. The solution is to process the scanner output as it arrives instead of waiting until we have it all.

**Comment by petterreinholdtsen** [comment] 2015-11-27 09:36
Yes.  I strace'd the master yesterday, and could see that it was busy running lstat() on destination files instead of reaping zombies.

**Comment by petterreinholdtsen** [comment] 2015-12-15 14:14
I believe this issue was fixed with pull request #63.

**Closed as completed by petterreinholdtsen** 2015-12-15 14:14 UTC
